dist: xenial
env:
  global:
    - HUGO_VERSION=0.53
before_install:
  - mkdir hugo
  - curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz -o hugo/hugo.tar.gz
  - (cd hugo && tar xzvf hugo.tar.gz)

script:
  - hugo/hugo version
  - (cd src && ../hugo/hugo -d ../dist)
