baseURL = "https://fernandoabolafio.github.io/dcrbounty"
title = "Decred Bug Bounty"
DefaultContentLanguage = "en"
copyright = "Decred Developers"
theme = "dcrbounty-theme"


[languages]
  [languages.en]
    languageName = "english"
    contentDir = "content/en"
    weight = 10

  [languages.pt]
    languageName = "português"
    contentDir = "content/pt"
    weight = 30

# Nav links in the top bar
[[menu.main]]
name = "Rules"
url = "rules/"
weight = 1
